version: '3.9'
services:
  pocketbase:
    image: augustodelg/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./pocketbase-data:/pb_data
      - ../pocketbase-migrations:/pb_migrations
