name: Alpha pipeline

on:
  push:
    branches:
      - alpha-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Generate version strings
        uses: '././github/actions/internal-version-string-generator'
        id: version-generator
        with:
          pre-release-label: alpha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jonfelixrico/marites-client:${{ steps.version-generator.outputs.docker }},jonfelixrico/marites-client:alpha
          build-args: BUILD_VERSION_OVERRIDE=${{ steps.version-generator.outputs.app }}
