name: On merge to master

on:
  push:
    branches:
      - master

jobs:
  verify:
    uses: './.github/workflows/verify-reusable.yml'

  build:
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Extract version components
        uses: './.github/actions/extract-semver-components'
        id: version
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            jonfelixrico/marites:latest
            jonfelixrico/marites:${{ steps.version.outputs.major }}
            jonfelixrico/marites:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
