name: On merge to dev

on:
  push:
    branches:
      - develop-*

jobs:
  verify:
    uses: './.github/workflows/verify-reusable.yml'

  build:
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Generate version strings
        uses: './.github/actions/internal-version-string-generator'
        id: version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            jonfelixrico/marites:alpha
            jonfelixrico/marites:alpha-${{ steps.version.outputs.major }}
            jonfelixrico/marites:alpha-${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
          build-args: BUILD_VERSION_OVERRIDE=${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}-alpha+${{ steps.version.outputs.sha }}
